Personal notes from DataCamp course [Writing Efficient Python Code course](https://www.datacamp.com/courses/writing-efficient-python-code#!)

$~$
________

$~$

# Writing Efficient Python Code:

Learn to write efficient code that executes quickly and allocates resources skillfully to avoid unnecessary overhead.

$~$

$~$

## 1. Foundations for efficiencies

$~$

In this chapter, you'll learn what it means to write efficient Python code. You'll explore Python's Standard Library, learn about NumPy arrays, and practice using some of Python's built-in tools. This chapter builds a foundation for the concepts covered ahead.

$~$

$~$ 

**Non-Pythonic** vs **Pythonic** ways of looping over a list

$~$ 

In [4]:
#here a simple list
names = ['Jerry', 'Kramer', 'Elaine', 'George', 'Newman']

$~$

Suppose we wanted to collect the names in the above list that **have six letters or more**. 

$~$

 + Non-Pythonic:


In [2]:
# Print the list created using the Non-Pythonic approach
i = 0
new_list= []
while i < len(names):
    if len(names[i]) >= 6:
        new_list.append(names[i])
    i += 1
print(new_list)

['Kramer', 'Elaine', 'George', 'Newman']


$~$

 +  Pythonic approach:

In [3]:
# Print the list created by looping over the contents of names
better_list = []
for name in names:
    if len(name) >= 6:
        better_list.append(name)
print(better_list)

['Kramer', 'Elaine', 'George', 'Newman']


$~$

 +  The best Pythonic way :


In [5]:
# Print the list created by using list comprehension
best_list = [name for name in names if len(name) >= 6]
print(best_list)

['Kramer', 'Elaine', 'George', 'Newman']


$~$

#### The Python standard library:

+ Buitl-in types:

    +  list, tuple, set, dict, and other

$~$

+ Built-in functions:

    + print(), len(), range(), round(), enumerate(), map(), zip(), etc.

$~$

+ Built-in functions:

    + os, sys, intertools, collections, math, and others
    


$~$

#### Built-in practice: **range()**

$~$

+ We can use **range()** in a few different ways:


    1) Create a sequence of numbers from 0 to a stop value (which is exclusive). This is useful when you want to create a simple sequence of numbers starting at zero.

    2) Create a sequence of numbers from a start value to a stop value (which is exclusive) with a step size.

In [10]:
# Create a range object that goes from 0 to 10
nums = range(11)
print(type(nums))

# Convert nums to a list
nums_list = list(nums)
print(nums_list)

# Create a new list of odd numbers from 1 to 20 by unpacking a range object
nums_list2 = [*range(1,21,2)]
print(nums_list2)

<class 'range'>
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
[1, 3, 5, 7, 9, 11, 13, 15, 17, 19]


*note that we can convert the range object into a list by using the list() function or by unpacking it into a list using the star character (*)*

$~$

#### Built-in practice: **enumerate()**

$~$

practice using Python's built-in function enumerate(). This function is useful for obtaining an indexed list. For example, suppose you had a list of people that arrived at a party you are hosting. 

$~$

In [12]:
#list of people ordered by arrival
names = ['Jerry', 'Kramer', 'Elaine', 'George', 'Newman']

indexed_names = []
for i,name in enumerate(names):
    print(i,name)

# Rewrite the above for loop using list comprehension
indexed_names_comp = [(i,name) for i,name in enumerate(names)]
print(indexed_names_comp)


# Unpack an enumerate object with a starting index of one
indexed_names_unpack = [*enumerate(names, 1)]
print(indexed_names_unpack)

0 Jerry
1 Kramer
2 Elaine
3 George
4 Newman
[(0, 'Jerry'), (1, 'Kramer'), (2, 'Elaine'), (3, 'George'), (4, 'Newman')]
[(1, 'Jerry'), (2, 'Kramer'), (3, 'Elaine'), (4, 'George'), (5, 'Newman')]


$~$

#### Built-in practice: **map()**

$~$

practice using Python's built-in map() function to apply a function to every element of an object. Suppose you wanted to create a new list (called names_uppercase) that converted all the letters in each name to uppercase. 

$~$

In [13]:
# Use map to apply str.upper to each element in names
names_map  = map(str.upper,names)

# Print the type of the names_map
print(type(names_map))

# Unpack names_map into a list
names_uppercase = [*names_map]

# Print the list created above
print(names_uppercase)

<class 'map'>
['JERRY', 'KRAMER', 'ELAINE', 'GEORGE', 'NEWMAN']


$~$

#### The power of NumPy arrays:

$~$

NumPy arrays provide a fast and memory efficient alternative to Python lists.

$~$

Let's practice slicing numpy arrays and using NumPy's broadcasting concept. 

In [14]:
# list num 
num = [[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]]

In [19]:
#import numpy
import numpy as np

nums = np.array(num)


In [20]:
# Print second row of nums
print(nums[1,:])

# Print all elements of nums that are greater than six
print(nums[nums > 6])

# Double every element of nums
nums_dbl = nums * 2
print(nums_dbl)

# Replace the third column of nums
nums[:,2] = nums[:,2] + 1
print(nums)

[ 6  7  8  9 10]
[ 7  8  9 10]
[[ 2  4  6  8 10]
 [12 14 16 18 20]]
[[ 1  2  4  4  5]
 [ 6  7  9  9 10]]


$~$

#### Bringing it all together: Festivus!

$~$

In [24]:
# Create a list of arrival times
arrival_times = [*range(10, 51, 10)]

print(arrival_times)

# Create a list of arrival times
arrival_times = [*range(10,60,10)]

# Convert arrival_times to an array and update the times
arrival_times_np = np.array(arrival_times)
new_times = arrival_times_np - 3

# Use list comprehension and enumerate to pair guests to new times
guest_arrivals = [(names[i],time) for i,time in enumerate(new_times)]

print(guest_arrivals)

[10, 20, 30, 40, 50]
[('Jerry', 7), ('Kramer', 17), ('Elaine', 27), ('George', 37), ('Newman', 47)]
